/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JualRouteImport } from './routes/jual'
import { Route as ProdukProductIdRouteImport } from './routes/produk.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JualRoute = JualRouteImport.update({
  id: '/jual',
  path: '/jual',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukProductIdRoute = ProdukProductIdRouteImport.update({
  id: '/produk/$productId',
  path: '/produk/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jual': typeof JualRoute
  '/produk/$productId': typeof ProdukProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jual': typeof JualRoute
  '/produk/$productId': typeof ProdukProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jual': typeof JualRoute
  '/produk/$productId': typeof ProdukProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jual' | '/produk/$productId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jual' | '/produk/$productId'
  id: '__root__' | '/' | '/jual' | '/produk/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JualRoute: typeof JualRoute
  ProdukProductIdRoute: typeof ProdukProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jual': {
      id: '/jual'
      path: '/jual'
      fullPath: '/jual'
      preLoaderRoute: typeof JualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$productId': {
      id: '/produk/$productId'
      path: '/produk/$productId'
      fullPath: '/produk/$productId'
      preLoaderRoute: typeof ProdukProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JualRoute: JualRoute,
  ProdukProductIdRoute: ProdukProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
